export const GET_ALL_CAKES_REQUEST = 'GET_ALL_CAKES_REQUEST';
export const GET_ALL_CAKES_SUCCESS = 'GET_ALL_CAKES_SUCCESS';
export const GET_ALL_CAKES_ERROR = 'GET_ALL_CAKES_ERROR';
export const GET_SINGLE_CAKE_REQUEST = 'GET_SINGLE_CAKE_REQUEST';
export const GET_SINGLE_CAKE_SUCCESS = 'GET_SINGLE_CAKE_SUCCESS';
export const GET_SINGLE_CAKE_ERROR = 'GET_SINGLE_CAKE_ERROR';
export const ADD_CAKE_SUCCESS = 'ADD_CAKE_SUCCESS';
export const ADD_CAKE_ERROR = 'ADD_CAKE_ERROR';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';

